# Generated by Django 5.2.2 on 2025-06-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agendablock'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='motivo_recusa_documentos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando aprovação'), ('documentos_aprovados', 'Documentos aprovados'), ('documentos_recusados', 'Documentos recusados'), ('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando_aprovacao', max_length=30),
        ),
    ]
