# Generated by Django 5.2.2 on 2025-06-12 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_motivo_recusa_documentos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemissaoProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=255)),
                ('exame', models.CharField(max_length=50)),
                ('status', models.CharField(default='aguardando_aprovacao', max_length=50)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('sindicato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.union')),
            ],
        ),
    ]
