# Generated by Django 5.2.2 on 2025-07-18 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_demissaoprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='demissaoprocess',
            name='motivo_recusa_documentos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='ressalvas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='demissao_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.demissaoprocess'),
        ),
        migrations.AlterField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
    ]
