# Generated by Django 5.2.2 on 2025-07-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_demissaoprocess_motivo_recusa_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rejeitado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('demissao_process', 'type')},
        ),
    ]
