# Generated by Django 5.2.2 on 2025-07-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_document_aprovado_em_document_motivo_recusa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demissaoprocess',
            name='data_rejeicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
