# Generated by Django 5.2.2 on 2025-07-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_demissaoprocess_data_rejeicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='video_link',
            field=models.URLField(blank=True, help_text='Link da videoconferência (Google Meet)', null=True),
        ),
    ]
