# Generated by Django 5.2.2 on 2025-07-18 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_schedule_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='union_user',
            field=models.ForeignKey(blank=True, help_text='Usuário do sindicato responsável pelo agendamento', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
