# Generated by Django 5.2.2 on 2025-07-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_schedule_union_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='demissaoprocess',
            name='video_link',
            field=models.URLField(blank=True, help_text='Link da videoconferência (Google Meet)', null=True),
        ),
    ]
