# Generated by Django 5.2.2 on 2025-07-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_demissaoprocess_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='demissaoprocess',
            name='assinado_empresa',
            field=models.BooleanField(default=False, help_text='Empresa confirmou assinatura'),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='assinado_sindicato',
            field=models.BooleanField(default=False, help_text='Sindicato confirmou assinatura'),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='data_assinatura_empresa',
            field=models.DateTimeField(blank=True, help_text='Data da assinatura pela empresa', null=True),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='data_assinatura_sindicato',
            field=models.DateTimeField(blank=True, help_text='Data da assinatura pelo sindicato', null=True),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='documento_assinado_empresa',
            field=models.FileField(blank=True, help_text='Documento assinado pela empresa', null=True, upload_to='assinaturas/empresa/'),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='documento_assinado_sindicato',
            field=models.FileField(blank=True, help_text='Documento assinado pelo sindicato', null=True, upload_to='assinaturas/sindicato/'),
        ),
    ]
