# Generated by Django 4.2.8 on 2025-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_demissaoprocess_assinado_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demissaoprocess',
            name='email_funcionario',
            field=models.EmailField(blank=True, help_text='Email do funcionário', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='telefone_funcionario',
            field=models.CharField(blank=True, help_text='Telefone do funcionário', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='Email do funcionário', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone do funcionário', max_length=20, null=True),
        ),
    ]
