# Generated by Django 4.2.8 on 2025-08-11 05:12

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_demissaoprocess_email_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demissaoprocess',
            name='documento_assinado_empresa',
            field=models.FileField(blank=True, help_text='Documento assinado pela empresa', null=True, upload_to='assinaturas/empresa/%Y/%m/', validators=[core.validators.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='demissaoprocess',
            name='documento_assinado_sindicato',
            field=models.FileField(blank=True, help_text='Documento assinado pelo sindicato', null=True, upload_to='assinaturas/sindicato/%Y/%m/', validators=[core.validators.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', validators=[core.validators.validate_document_file]),
        ),
    ]
