# Generated by Django 4.2.0 on 2024-01-01 00:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_demissaoprocess_documento_assinado_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='ID do evento no Google Calendar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='google_meet_conference_id',
            field=models.CharField(blank=True, help_text='ID da conferência no Google Meet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='google_meet_link',
            field=models.URLField(blank=True, help_text='Link direto para o Google Meet', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='google_calendar_link',
            field=models.URLField(blank=True, help_text='Link para o evento no Google Calendar', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='meeting_created_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora de criação da reunião no Google Meet', null=True),
        ),
    ]
