# Generated by Django 4.2.23 on 2025-08-14 14:26

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_schedule_google_meet_integration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='assinado_trabalhador',
            field=models.BooleanField(default=False, help_text='Trabalhador confirmou assinatura'),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='data_assinatura_trabalhador',
            field=models.DateTimeField(blank=True, help_text='Data da assinatura pelo trabalhador', null=True),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='documento_assinado_trabalhador',
            field=models.FileField(blank=True, help_text='Documento assinado pelo trabalhador', null=True, upload_to='assinaturas/trabalhador/%Y/%m/', validators=[core.validators.validate_pdf_file]),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='employee_upload_expires',
            field=models.DateTimeField(blank=True, help_text='Validade do token de upload do trabalhador', null=True),
        ),
        migrations.AddField(
            model_name='demissaoprocess',
            name='employee_upload_token',
            field=models.CharField(blank=True, help_text='Token público para upload do trabalhador', max_length=64, null=True),
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='core_schedule',
        ),
    ]
