# Generated by Django 5.2.5 on 2025-09-04 18:00

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_worker_signature_and_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demissaoprocess',
            name='documento_assinado_trabalhador',
            field=models.FileField(blank=True, help_text='Documento assinado pelo trabalhador', null=True, upload_to='assinaturas/trabalhador/%Y/%m/', validators=[core.validators.validate_pdf_file]),
        ),
    ]
