# Generated by Django 5.2.5 on 2025-09-07 03:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_demissaoprocess_documento_assinado_trabalhador'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('action', models.CharField(blank=True, choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('COMPANY_CREATED', 'Company Created'), ('COMPANY_UPDATED', 'Company Updated'), ('COMPANY_DELETED', 'Company Deleted'), ('UNION_CREATED', 'Union Created'), ('UNION_UPDATED', 'Union Updated'), ('UNION_DELETED', 'Union Deleted'), ('SCHEDULE_CREATED', 'Schedule Created'), ('SCHEDULE_UPDATED', 'Schedule Updated'), ('SCHEDULE_DELETED', 'Schedule Deleted'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_APPROVED', 'Document Approved'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('HOMOLOGATION_COMPLETED', 'Homologation Completed'), ('SYSTEM_ERROR', 'System Error'), ('API_CALL', 'API Call'), ('SECURITY_EVENT', 'Security Event')], max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Dados adicionais em formato JSON', null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.company')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.schedule')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.union')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='core_system_timesta_7e67e4_idx'), models.Index(fields=['level'], name='core_system_level_bf5286_idx'), models.Index(fields=['action'], name='core_system_action_93696a_idx'), models.Index(fields=['user'], name='core_system_user_id_6f81b7_idx')],
            },
        ),
    ]
