# Generated by Django 5.2.5 on 2025-09-10 21:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_systemlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_original', models.FileField(upload_to='signing/original/')),
                ('pdf_final', models.FileField(blank=True, null=True, upload_to='signing/signed/')),
                ('hash_original', models.CharField(blank=True, max_length=128)),
                ('hash_final', models.CharField(blank=True, max_length=128)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sign_sessions', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_sessions', to='core.schedule')),
            ],
            options={
                'verbose_name': 'Sessão de Assinatura',
                'verbose_name_plural': 'Sessões de Assinatura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COMPANY', 'Empresa'), ('UNION', 'Sindicato'), ('EMPLOYEE', 'Funcionário')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_user_agent', models.TextField(blank=True)),
                ('magic_link_token', models.CharField(blank=True, max_length=512)),
                ('magic_link_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_hash', models.CharField(blank=True, max_length=128)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='signing.signingsession')),
            ],
            options={
                'verbose_name': 'Parte da Assinatura',
                'verbose_name_plural': 'Partes da Assinatura',
                'unique_together': {('session', 'role')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SESSION_CREATED', 'Sessão Criada'), ('PDF_UPLOADED', 'PDF Enviado'), ('PARTIES_DEFINED', 'Partes Definidas'), ('EMPLOYEE_LINK_GENERATED', 'Link do Funcionário Gerado'), ('OTP_SENT', 'OTP Enviado'), ('OTP_VERIFIED', 'OTP Verificado'), ('CONSENT_GIVEN', 'Consentimento Dado'), ('SIGNED', 'Assinado'), ('FINAL_SEAL', 'Selo Final Criado'), ('FINALIZED', 'Finalizado')], max_length=64)),
                ('timestamp_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signing.party')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='signing.signingsession')),
            ],
            options={
                'verbose_name': 'Evento de Evidência',
                'verbose_name_plural': 'Eventos de Evidência',
                'ordering': ['timestamp_utc'],
            },
        ),
    ]
